### PR TITLE
start unit testing, provide baseline perf

### PR DESCRIPTION
**Pull request by efx**
This also fixes running the test suite as including
`ember-load-initializers` in `package.json` short circuited resolving
the addon's version. 

Adding all the mock initializer files feels wrong, but it seemed to be the quickest and most accurate way to simulate production applications from within the unit tests. I tried stubbing `require._eak_seen` but that seemed more trouble than it is worth.

### CODE REVIEW

**Comment by rwjblue** [comment]
Instead of including the files in the repo, maybe we can generate the extra files on demand? Something like a script to generate simulated modules based on real life data sets (e.g. `Object.keys(requirejs.entries)` from `travis-ci.org`, `linkedin.com`, `percy.io`, `my.freshbooks.com`, `store.nest.com`, `emberobserver.com`, etc...).  Using real data sets is important because the ratio of "hits" (initializer file) vs "misses" (non-initializer file) is pretty important.

What do you think?

**Comment by efx** [comment]
@rwjblue Grabbing the keys from those sites would better capture real world scenarios. I can see dynamically generating them in the test is much easier to think about too.

I'll take a stab at updating.

**Comment by rwjblue** [comment]
Ya, I was thinking that we could grab them once and just keep the arrays in JSON blobs here in the repo...

**Comment by efx** [comment]
@rwjblue happy new year :). Thoughts on the update as a baseline perf test?

**Comment by efx** [comment]
@rwjblue would you mind reviewing this if you are free?

**Comment by efx** [comment]
closing for lack of activity.

**Pull request closed without merging**
